on:
  push:
    branches: [ master ]
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Auto Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2

    - name: 📂 Sync files
      uses: appleboy/ssh-action@v0.1.7
      with:
        switches: -avzr --delete --exclude=".git" --exclude=".github"
        path: /
#         remote_path: /home/radenfebri/cicd
#         remote_host: 103.150.87.242
#         remote_user: radenfebri
#         remote_key: Febri2303
        
        host: 103.150.87.242
        username: radenfebri
        password: Febri2303
        port: 22
        script: whoami
        
        
        
        
        name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: whoami
