name: CI

on:
  push:
    branches: [ master ]

jobs:
  build: 
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: youtube-radenfebri.my.id
          username: radenfebri
          key: ${{ secrets.remote_key }}
          port: 22
          script:
            cd /home/radenfebri/website
            git pull origin master
            git status
          
      
